const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const sourceDir = path.join(root, "src");
const outputFile = path.join(root, "MedCut.js");

const orderedFiles = [
  "00-config.js",
  "10-storage.js",
  "20-core.js",
  "30-widget.js",
  "40-dashboard.js",
  "50-prompts.js",
  "99-main.js"
];

function readSource(fileName) {
  const filePath = path.join(sourceDir, fileName);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing source file: ${fileName}`);
  }
  return fs.readFileSync(filePath, "utf8").trimEnd();
}

const banner = [
  "// Generated from src/*.js by scripts/build.js.",
  "// Do not edit this file directly; edit the source files and run `npm run build`."
].join("\n");

const bundle = [banner]
  .concat(orderedFiles.map(readSource))
  .join("\n\n") + "\n";

fs.writeFileSync(outputFile, bundle);
console.log(`Built ${path.relative(root, outputFile)} from ${orderedFiles.length} source files.`);
